### ISSUE TITLE
SOS, but not really :)

### ISSUE THREAD

**Issue by wafaajaunnoo** [houzyk/thephilosophicalcode#1]
Hey! Is it okay if my only references are two youtube videos and my brain?

**Comment by houzyk** [comment]
Asalam, yes totally ok! Reminds me that I should really update these contribution guidelines.

**Comment by houzyk** [comment]
Contribution guidelines updated

**Comment by wafaajaunnoo** [comment]
Wa'alaikoumoussalaam.  perfect, thanks!
