### ISSUE TITLE
New Favicon

### ISSUE THREAD

**Issue by houzyk** [houzyk/thephilosophicalcode#6]
Currently, the favicon in feature/astro-migration is a default one. Need a custom one to be added to public/

**Comment by veegishx** [comment]
I'll take this one, thanks

**Comment by houzyk** [comment]
@veegishx  branch: feature/new-favicon. Thanks dude!

**Comment by houzyk** [comment]
Btw,  feature/astro-migration is already merged on main and feature/new-favicon is from main itself
