### ISSUE TITLE
Add "Stuff" page

### ISSUE THREAD

**Issue by houzyk** [houzyk/thephilosophicalcode#9]
- Add stuff page for reading list
- Add link in header
- Add SEO

**Comment by diouman** [comment]
Taking this request.

**Comment by houzyk** [comment]
Dummy data:


## Logic

1. [a link](https://www.google.com)
2. [a link](https://www.google.com)
3. [a link](https://www.google.com)
4. [a link](https://www.google.com)
5. [a link](https://www.google.com)

## Philosophy

1. [a link](https://www.google.com)
2. [a link](https://www.google.com)
3. [a link](https://www.google.com)
4. [a link](https://www.google.com)
5. [a link](https://www.google.com)


## TCS

1. [a link](https://www.google.com)
2. [a link](https://www.google.com)
3. [a link](https://www.google.com)
4. [a link](https://www.google.com)
5. [a link](https://www.google.com)


## Automata

1. [a link](https://www.google.com)
2. [a link](https://www.google.com)
3. [a link](https://www.google.com)
4. [a link](https://www.google.com)
5. [a link](https://www.google.com)

**Comment by diouman** [comment]
PR: https://github.com/houzyk/thephilosophicalcode/pull/29
